#!/bin/bash
#export CODE='/mnt/c/Users/paulw/Desktop/School/NCSSM/Junior/T1/Programming/FinalProject/chitchat/src/main/java/io/github/chitchat/*.java'
#export NETTY='/home/lucror/netty-4.1.54.Final/jar/all-in-one/netty-all-4.1.54.Final.jar'
#javac -d . -cp $NETTY $CODE

javac -d . -cp ./lib/netty-all-4.1.54.Final.jar src/io/github/chitchat/*.java
